apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
data:
  pelias.json: |
    {
      "esclient": {
        "hosts": [
          {
            "env": "development",
            "protocol": "http",
            "host": "localhost",
            "port": 9200
          }
        ]
      },
      "api": {
        "targets": {
          "layers_by_source": {
            "nsr": [
              "stop_place",
              "stop_place_child",
              "stop_place_parent"
            ]
          },
          "csv": [
            "address"
          ]
        }
      },
      "logger": {
        "level": "debug"
      },
      "imports": {
        "adminLookup": {
          "enabled": false
        },
        "csv": {
          "datapath": "/home/importer/csv"
        }
      }
    }