apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  name: cronjob-redeploy-{{ template "app.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  concurrencyPolicy: {{ .Values.cronjobRedeployMoradin.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.cronjobRedeployMoradin.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - ./redeploy_on_change_deployment.sh
              env:
                - name: TZ
                  value: Europe/Oslo
                - name: CLOUDSDK_CORE_PROJECT
                  value: {{ .Values.cronjobRedeployMoradin.cloudsdkCoreProject }}
                - name: CURRENT_FILE_PATH
                  value: {{.Values.gcsBasePath}}current
                - name: LAST_FILE_PATH
                  value: {{.Values.gcsBasePath}}last
                - name: DEPLOYMENT
                  value: {{ template "app.name" . }}
                - name: CREDENTIALS_FILE_PATH
                  value: {{ .Values.secretMount.mountPath }}
                - name: SLACK_URL
                  valueFrom:
                    secretKeyRef:
                      key: slack-url
                      name: {{ .Values.cronjobRedeployMoradin.slackName }}
              image: {{ .Values.cronjobRedeployMoradin.image.repo }}
              imagePullPolicy: IfNotPresent
              name: job-redeploy-moradin
              resources:
                limits:
                  cpu: {{ .Values.cronjobRedeployMoradin.resources.cpuLimit }}
                  memory: {{ .Values.cronjobRedeployMoradin.resources.memLimit }}
                requests:
                  cpu: {{ .Values.cronjobRedeployMoradin.resources.cpuRequest }}
                  memory: {{ .Values.cronjobRedeployMoradin.resources.memRequest }}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - name: {{ .Values.secretMount.name }}
                  mountPath: {{ .Values.secretMount.mountPath }}
                  subPath: {{ .Values.secretMount.subPath }}
                  readOnly: {{ .Values.secretMount.readOnly }}
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
          volumes:
            - name: {{ .Values.secretMount.name }}
              secret:
                secretName: {{ .Values.secretMount.secretName }}
  schedule: '0/30 * * * *'
  successfulJobsHistoryLimit: {{ .Values.cronjobRedeployMoradin.successfulJobsHistoryLimit }}
  suspend: false
