apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-redeploy-{{ template "app.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
    app: cronjob-redeploy-{{ template "app.name" . }}
spec:
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - ./redeploy_generic_deployment.sh
              env:
                - name: TZ
                  value: Europe/Oslo
                - name: CLOUDSDK_CORE_PROJECT
                  value: {{ .Values.cronjob.cloudsdkCoreProject }}
                - name: DEPLOYMENT
                  value: {{ template "app.name" . }}
                - name: SLACK_URL
                  valueFrom:
                    secretKeyRef:
                      key: slack-url
                      name: {{ .Values.cronjob.slackName }}
              image: {{ .Values.cronjob.image.repo }}
              imagePullPolicy: IfNotPresent
              name: job-redeploy-{{ template "app.name" . }}
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: cronjob-redeploy-{{ template "app.name" . }}
          serviceAccountName: cronjob-redeploy-{{ template "app.name" . }}
          terminationGracePeriodSeconds: 30
  schedule: '0 0 * * *'
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  suspend: false
