apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "common.labels" . | indent 8 }}
    spec:
      containers:
        - name: elasticsearch
          image: {{ .Values.images.elasticsearch }}
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Europe/Oslo
          ports:
            - containerPort: 9200
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: _cluster/health?wait_for_status=yellow&timeout=120s
              port: 9200
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 30
          resources:
            limits:
              cpu: 1
              memory: 1600Mi
            requests:
              cpu: 1
              memory: 1600Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

        - name: {{ .Chart.Name }}-importer
          image: {{ .Values.images.importer.identifier }}
          imagePullPolicy: {{ .Values.images.importer.imagePullPolicy }}
          volumeMounts:
            - name: {{ .Values.secretMount.name }}
              mountPath: {{ .Values.secretMount.mountPath }}
              subPath: {{ .Values.secretMount.subPath }}
              readOnly: {{ .Values.secretMount.readOnly }}
            - name: application-config
              mountPath: /etc/application-config
              readOnly: true
          env:
            - name: GCS_BASE_PATH
              value: {{.Values.gcsBasePath}}
            - name: GCP_SA_KEY
              value: {{ .Values.secretMount.mountPath }}
            - name: PELIAS_CONFIG
              value: /etc/application-config/pelias.json
          resources:
            limits:
              cpu: 1
              memory: 1000Mi
            requests:
              cpu: 1
              memory: 1000Mi

        - name: {{ .Chart.Name }}-api
          image: {{ .Values.images.pelias }}
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Europe/Oslo
            - name: PORT
              value: "4000"
            - name: PELIAS_CONFIG
              value: /etc/application-config/pelias.json
          resources:
            limits:
              cpu: 1
              memory: 1000Mi
            requests:
              cpu: 1
              memory: 1000Mi
          ports:
            - containerPort: 4000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: status
              port: 4000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: application-config
              mountPath: /etc/application-config
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 45
      volumes:
        - name: {{ .Values.secretMount.name }}
          secret:
            secretName: {{ .Values.secretMount.secretName }}
        - name: application-config
          configMap:
            name: {{ template "app.name" . }}-config
            defaultMode: 420

