env: dev

replicas: 1

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0

resources:
  cpuLimit: "4"
  memLimit: 11264Mi
  cpuRequest: "3"
  memRequest: 11264Mi
  xmx: 30g

images:
  elasticsearch: pelias/elasticsearch:7.16.1
  moradin: ${artifact.metadata.image}
  imagePullPolicy: Always

service:
  http:
    externalPort: 80
    internalPort: 4000

horizontalPodAutoscaler:
  maxReplicas: 2
  minReplicas: 1
  targetCPUUtilizationPercentage: 80

cronjob:
  enabled: true
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  resources:
    cpuLimit: 900m
    memLimit: 2550Mi
    cpuRequest: 100m
    memRequest: 1000m
  image:
    repo: eu.gcr.io/entur-system-1287/deployment-rollout-restart:0.1.6

slackUrlSecret : ${serviceVariable.slackUrlSecret}