env: dev

replicas: 1

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0

resources:
  memLimit: 100Mi
  cpuRequest: 300m
  memRequest: 100m

images:
  elasticsearch: pelias/elasticsearch:7.16.1
  pelias: pelias/api:v5.53.0
  importer:
    identifier: ${artifact.metadata.image}
    imagePullPolicy: Always

secretMount:
  name: moradin-key
  mountPath: /etc/moradin/credentials.json
  subPath: credentials.json
  secretName: ror-moradin-sa-key
  readOnly: true

service:
  http:
    externalPort: 80
    internalPort: 4000

horizontalPodAutoscaler:
  maxReplicas: 2
  minReplicas: 1
  targetCPUUtilizationPercentage: 80