env: dev

replicas: 1

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0

resources:
  memLimit: 100Mi
  cpuRequest: 300m
  memRequest: 100m

images:
  elasticsearch: pelias/elasticsearch:7.16.1
  pelias: pelias/api:v5.53.0
  moradin: ${artifact.metadata.image}
  imagePullPolicy: Always

service:
  http:
    externalPort: 80
    internalPort: 4000

horizontalPodAutoscaler:
  maxReplicas: 2
  minReplicas: 1
  targetCPUUtilizationPercentage: 80

cronjob:
  enabled: true
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  resources:
    cpuLimit: 900m
    memLimit: 2550Mi
    cpuRequest: 100m
    memRequest: 1000m
  image:
    repo: eu.gcr.io/entur-system-1287/deployment-rollout-restart:0.1.6