apiVersion: v2
appVersion: "0.1.0"
description: geocoderv2
name: moradin
version: 0.1.0
keywords:
- moradin
- geocoderv2
sources:
- https://github.com/entur/moradin
maintainers:
- name: 'team-ror'
  email: team.rutedata@entur.org
dependencies:
  - name: common
    version: 1.2.5
    repository: "https://entur.github.io/helm-charts"
