name: Build and push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  docker-build:
    if: github.repository_owner == 'entur' && github.event_name == 'push' && github.ref == 'refs/heads/master'
    uses: entur/gha-docker/.github/workflows/build.yml@v1
  docker-push:
    needs: [docker-build]
    uses: entur/gha-docker/.github/workflows/push.yml@v1